//LOAD DATA
export const LOADING_DATA = 'LOADING_DATA'

//CATEGORIES
export const LOAD_CATS = 'LOAD_CATS'

//POSTS
export const LOAD_POSTS = 'LOAD_POSTS'
export const DISPLAY_POSTS = 'DISPLAY_POSTS'
export const SORT_POSTS = 'SORT_POSTS'
//POST ACTIONS
export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const VOTE_POST = 'VOTE_POST'

//COMMENTS
export const LOAD_COMMENTS = 'LOAD_COMMENTS'
//COMMENT ACTIONS
export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const VOTE_COMMENT = 'VOTE_COMMENT'
//COMMENT FORM ACTIONS
export const DISPLAY_COMMENT_FORM = 'DISPLAY_COMMENT_FORM'
export const HIDE_COMMENT_FORM = 'HIDE_COMMENT_FORM'
